const configured=window.GH_SUPABASE_URL&&!window.GH_SUPABASE_URL.startsWith("VUL_");
const client=configured?window.supabase.createClient(window.GH_SUPABASE_URL,window.GH_SUPABASE_PUBLISHABLE_KEY):null;
const $=id=>document.getElementById(id);let chapters=[],articles=[],activeChapter="",currentUser=null;
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function slugify(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
async function verifyAdmin(user){const{data}=await client.from("admins").select("user_id").eq("user_id",user.id).maybeSingle();return!!data}
async function showSession(){if(!configured){$("loginMessage").textContent="Vul eerst supabase-config.js in.";return}const{data:{session}}=await client.auth.getSession();if(session&&await verifyAdmin(session.user)){currentUser=session.user;$("loginView").hidden=true;$("adminView").hidden=false;$("logoutButton").hidden=false;await loadData()}else{$("loginView").hidden=false;$("adminView").hidden=true;$("logoutButton").hidden=true}}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMessage").textContent="Bezig met inloggen...";const{data,error}=await client.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error){$("loginMessage").textContent=error.message;return}if(!await verifyAdmin(data.user)){await client.auth.signOut();$("loginMessage").textContent="Dit account heeft geen beheerdersrechten.";return}await showSession()};
$("logoutButton").onclick=async()=>{await client.auth.signOut();location.reload()};
async function loadData(){const[c,a]=await Promise.all([client.from("chapters").select("*").order("sort_order"),client.from("articles").select("*").order("sort_order")]);chapters=c.data||[];articles=a.data||[];renderChapters();renderArticles();fillChapterSelect()}
function renderChapters(){$("adminChapterList").innerHTML=chapters.map(c=>`<button class="chapter-admin ${activeChapter===c.id?"active":""}" data-id="${c.id}">${c.icon||"▤"} ${c.title}</button>`).join("");document.querySelectorAll(".chapter-admin").forEach(b=>b.onclick=()=>{activeChapter=b.dataset.chapter??b.dataset.id??"";document.querySelectorAll(".chapter-admin").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderArticles()})}
function renderArticles(){const q=$("adminSearch").value.toLowerCase();const list=articles.filter(a=>(!activeChapter||a.chapter_id===activeChapter)&&(!q||`${a.article_number} ${a.title}`.toLowerCase().includes(q)));$("articleTable").innerHTML=list.map(a=>`<div class="article-row"><b>${a.article_number}</b><div><strong>${a.title}</strong><small>${a.is_published?"Gepubliceerd":"Concept"}</small></div><span>${a.jail||"—"}</span><span>${a.fine||"—"}</span><div class="row-actions"><button data-edit="${a.id}">Bewerken</button><button data-delete="${a.id}">Verwijderen</button></div></div>`).join("")||"<p>Geen artikelen gevonden.</p>";document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openArticle(articles.find(a=>a.id===b.dataset.edit)));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteArticle(b.dataset.delete))}
$("adminSearch").oninput=renderArticles;
function fillChapterSelect(){$("articleChapter").innerHTML=chapters.map(c=>`<option value="${c.id}">${c.title}</option>`).join("")}
function openArticle(a={}){$("articleDialogTitle").textContent=a.id?"Artikel bewerken":"Nieuw artikel";$("articleId").value=a.id||"";$("articleChapter").value=a.chapter_id||chapters[0]?.id||"";$("articleNumber").value=a.article_number||"";$("articleTitle").value=a.title||"";$("articleDescription").value=a.description||"";$("articleJail").value=a.jail||"";$("articleFine").value=a.fine||"";$("articlePoints").value=a.points||"";$("articleSeize").value=a.seize||"";$("articleSeverity").value=a.severity||"normaal";$("articleOrder").value=a.sort_order||0;$("articleTags").value=(a.tags||[]).join(", ");$("articlePublished").checked=a.is_published!==false;$("articleDialog").showModal()}
$("newArticleButton").onclick=()=>openArticle();
$("articleForm").onsubmit=async e=>{e.preventDefault();const id=$("articleId").value;const payload={chapter_id:$("articleChapter").value,article_number:$("articleNumber").value.trim(),title:$("articleTitle").value.trim(),description:$("articleDescription").value,jail:$("articleJail").value,fine:$("articleFine").value,points:$("articlePoints").value,seize:$("articleSeize").value,severity:$("articleSeverity").value,sort_order:Number($("articleOrder").value)||0,tags:$("articleTags").value.split(",").map(x=>x.trim()).filter(Boolean),is_published:$("articlePublished").checked,updated_by:currentUser.id};const result=id?await client.from("articles").update(payload).eq("id",id):await client.from("articles").insert(payload);if(result.error){alert(result.error.message);return}$("articleDialog").close();toast("Artikel opgeslagen.");await loadData()}
async function deleteArticle(id){if(!confirm("Dit artikel echt verwijderen?"))return;const{error}=await client.from("articles").delete().eq("id",id);if(error){alert(error.message);return}toast("Artikel verwijderd.");await loadData()}
function openChapter(c={}){$("chapterId").value=c.id||"";$("chapterTitle").value=c.title||"";$("chapterSlug").value=c.slug||"";$("chapterIcon").value=c.icon||"";$("chapterDescription").value=c.description||"";$("chapterOrder").value=c.sort_order||0;$("chapterPublished").checked=c.is_published!==false;$("chapterDialog").showModal()}
$("newChapterButton").onclick=()=>openChapter();
$("chapterTitle").oninput=()=>{if(!$("chapterId").value)$("chapterSlug").value=slugify($("chapterTitle").value)};
$("chapterForm").onsubmit=async e=>{e.preventDefault();const id=$("chapterId").value;const payload={title:$("chapterTitle").value.trim(),slug:$("chapterSlug").value.trim(),icon:$("chapterIcon").value,description:$("chapterDescription").value,sort_order:Number($("chapterOrder").value)||0,is_published:$("chapterPublished").checked};const result=id?await client.from("chapters").update(payload).eq("id",id):await client.from("chapters").insert(payload);if(result.error){alert(result.error.message);return}$("chapterDialog").close();toast("Hoofdstuk opgeslagen.");await loadData()}
$("importButton").onclick=async()=>{if(!confirm("De huidige JSON importeren? Gebruik dit alleen bij een lege database."))return;const r=await fetch("../data/wetboek.json");const j=await r.json();for(let i=0;i<j.chapters.length;i++){const c=j.chapters[i];const{data:chapter,error}=await client.from("chapters").insert({title:c.title,slug:c.id,icon:c.icon||"▤",description:c.description||"",sort_order:i,is_published:true}).select().single();if(error){alert(error.message);return}for(let x=0;x<c.articles.length;x++){const a=c.articles[x];const{error:ae}=await client.from("articles").insert({chapter_id:chapter.id,article_number:a.number,title:a.title,description:a.description||"",jail:a.penalty?.jail||"",fine:a.penalty?.fine||"",points:a.penalty?.points||"",seize:a.penalty?.seize||"",tags:a.tags||[],severity:a.severity||"normaal",sort_order:x,is_published:true,updated_by:currentUser.id});if(ae){alert(ae.message);return}}}toast("Import voltooid.");await loadData()}
showSession();